controller_manager:
  ros__parameters:
    update_rate: 50  # Update rate in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_position_controller:
      type: position_controllers/JointGroupPositionController

joint_position_controller:
  ros__parameters:
    joints:
      - elevator_joint  # Ensure this matches the joint name in your URDF
    command_interfaces:
      - position
    state_interfaces:
      - position

